### ISSUE TITLE
Energy Sword Suggestion

### ISSUE THREAD

**Issue by Gamerbolts** [AzureDoom/MCHalo#2]
I went to change damage values for the weapons and found that the energy sword was not in the config file. It is very OP and one hits everything in my modpack. Is there a chance you put that in the config file? Or a way to change receipts to make it harder to obtain?

**Comment by AzureDoom** [comment]
The recipe is already configurable via the datapack.

**Comment by Gamerbolts** [comment]
Ah didn't know that. Ok thanks!
