### ISSUE TITLE
Brute Shot Ammo

### ISSUE THREAD

**Issue by Gamerbolts** [AzureDoom/MCHalo#3]
Hi there, was playing around with the mod and testing the guns. The brute shot I am assuming reloads with grenades but I have grenades in my inventory and an empty clip yet "R" will not reload the gun. All other guns reload just fine.

**Comment by AzureDoom** [comment]
Crap >.> yeah, totally left the packet it for empty
https://github.com/AzureDoom/MCHalo/blob/1.18/src/main/java/mod/azure/mchalo/MCHaloMod.java#L147-L152
