### ISSUE TITLE
Items not able to apply Mending from Mending Levels

### ISSUE THREAD

**Issue by Gamerbolts** [AzureDoom/MCHalo#6]
Hello! I am working on a modpack and did some extensive research after a user let me know the Mending Levels mod which adds books of different levels that can be applied to weapons and armor. I have the following mods and versions installed and whenever I put any items in the anvil with Mending it will not work.

Fabric 1.18.2 0.14.8
Cloth Config API v6.2.62
Fabric API v0.57.0
GeckoLib v3.0.50
MCHalo v1.0.2
Mending Levels v1.0.1

Here is my [latest.log](https://github.com/AzureDoom/MCHalo/files/9060446/latest.log) if that helps. I will also post this on the Mending Levels github to see if it is on their end. Thank you!

**Comment by AzureDoom** [comment]
1.18.2 is unsupported with the release of 1.19 version. I only support latest MC version.
