### ISSUE TITLE
1.18.2 not able to use Mending or Unbreaking books

### ISSUE THREAD

**Issue by TheRealPicasso** [AzureDoom/MCHalo#8]
This Mod caused, that i couldnt use Mending and unbreaking books in my worlds. I dont know why but i hope you could research and fix it. Thanks!

**Comment by AzureDoom** [comment]
1.18.2 is unsupported

**Comment by TheRealPicasso** [comment]
> 1.18.2 is unsupported

not going to update it anytime?

**Comment by AzureDoom** [comment]
It's almost like I said I don't support 1.18.2 anymore or something. Words must be hard for you. Let me explain in words you might understand. 

You, dumb dumb, me no work on 1.18.2. Me no fix thing me don't work on anymore.
